name: README generator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      
      - name: Debug - list files
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Contents of root ==="
          ls -la
          echo "=== Contents of .github/scripts/ ==="
          ls -la .github/scripts/ || echo "Folder doesn't exist!"
          echo "=== Find all Python files ==="
          find . -name "*.py"
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure Python
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate README
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          python .github/scripts/generator.py

      - name: Push README
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Daily README generation"
          file_pattern: "README.md"
